apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::304314125137:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::304314125137:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JTQF43WGIOZD
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-12-25T20:56:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1569"
  uid: b912aa1c-701d-4cc4-9edb-075ef511dc37
